apiVersion: apps/v1
kind: Deployment
metadata:
  name: yahoo-finance-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yahoo-finance
  template:
    metadata:
      labels:
        app: yahoo-finance
    spec:
      containers:
      - name: yahoo-finance
        image: <your_ecr_or_local_image>
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: RAW_S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: yahoo-finance-config
              key: RAW_S3_BUCKET
        - name: TRANSFORMED_S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: yahoo-finance-config
              key: TRANSFORMED_S3_BUCKET